version: '2'
services:

    mysql:
      image: mysql
      ports:
        - 3307:3306
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./dbutil:/docker-entrypoint-initdb.d
      networks:
            - default_network_name

    stock:
      image: stock-service-docker
      ports:
        - 8080:8080
      networks:
            - default_network_name

networks:
    default_network_name:
        driver: bridge