package main

import (
	"gopkg.in/urfave/cli.v1"
	"os"
)

var (
	appName string = "stock-service"
	version string = "0.0.0"
)

func main() {
	app := cli.NewApp()
	app.Name = appName
	app.Version = version
	app.Copyright = "(c) 2017 - Dafiti Group"
	app.Usage = "Stock service is a small app to deal with stock and stock reservation"
	app.Flags = []cli.Flag{
		cli.StringFlag{
			Name:   "listen, l",
			Value:  "0.0.0.0:8000",
			Usage:  "Address and port on which Stock Service will accept HTTP requests",
			EnvVar: "LISTEN",
		},
		cli.StringFlag{
			Name:   "log-folder, lf",
			Value:  "",
			Usage:  `Log folder path for access and application logging. Default "stdout"`,
			EnvVar: "LOG_FOLDER",
		},
		cli.StringFlag{
			Name:   "newrelic-appname",
			Value:  app.Name,
			Usage:  "NewRelic application name, this flag is required for NewRelic instrumentation",
			EnvVar: "NEWRELIC_APPNAME",
		},
		cli.StringFlag{
			Name:   "newrelic-license-key",
			Value:  "",
			Usage:  "NewRelic license key, this flag is required for NewRelic instrumentation",
			EnvVar: "NEWRELIC_LICENSE_KEY",
		},
		cli.StringFlag{
			Name:   "revision-file",
			Value:  "",
			Usage:  "Expose the revision file generated by build into url",
			EnvVar: "REVISION_FILE",
		},
		cli.StringFlag{
			Name:   "database-file",
			Value:  "",
			Usage:  "Database configuration used by Stock Service to connect to database",
			EnvVar: "DATABASE_FILE",
		},
		cli.StringFlag{
			Name:   "swagger-file",
			Value:  "",
			Usage:  "Expose the swagger file",
			EnvVar: "SWAGGER_FILE",
		},
	}

	app.Commands = []cli.Command{
		cli.Command{
			Name:   "check",
			Usage:  "Check if the configuration and dependencies are ok",
			Action: Check,
		},
	}

	app.Action = Serve

	app.Run(os.Args)
}
